### ISSUE TITLE
Error in read.dets() emerging with update to R v4.2.0

### ISSUE THREAD

**Issue by nickmckay** [Maarten14C/rbacon#5]
Versions of R > 4.2 seem to have gotten stricter with boolean tests with multiple values, resulting in errors that used to be warnings (I think). One such example has shown up for me a couple times in `read.dets()`. Check out the error report below - I can probably create a simple reproducible example if the problem/solution is tricky to diagnose.

Thanks!

 ----------- FAILURE REPORT -------------- 
   --- failure: length > 1 in coercion to logical ---
   --- srcref --- 
  : 
   --- package (from environment) --- 
  rbacon
   --- call from context --- 
  read.dets(core, coredir, sep = sep, dec = dec, cc = cc)
   --- call from argument --- 
  name[5] %in% cc.names && min(dets[, 5]) >= 0 && max(dets[, 5]) <= 
      4 && range(dets[, 9] - dets[, 8]) == c(1, 1)
   --- R stacktrace ---
  where 1: read.dets(core, coredir, sep = sep, dec = dec, cc = cc)
  where 2: rbacon::Bacon(core = site.name, coredir = bacon.dir, thick = thick, 
      acc.mean = bacon.acc.mean, ...)

**Comment by Maarten14C** [comment]
hmmm difficult one, I think I spotted where there could be lengths >1. Testing this on a remote system with R 4.2. Thanks for spotting this.

**Comment by GPawi** [comment]
Hi @Maarten14C  and @nickmckay 
I am currently running into the same problem. I got an error message saying:
`<simpleError in if (info$cc > 0) if (info$postbomb == 0 && ((ncol(info$dets) ==     4 && min(info$dets[, 2]) < 0) || ncol(info$dets) > 4 && max(info$dets[,     5]) > 0 && min(info$dets[info$dets[, 5] > 0, 2]) < 0)) stop("you have negative C14 ages so should select a postbomb curve",     call. = FALSE): the condition has length > 1>` 

So I assume the issue is here: https://github.com/Maarten14C/rbacon/blob/82d9b58d9e8c744a45fcfabe39de329a3c41363c/R/Bacon.R#L273-L279

Does anyone of you have a solution or a workaround? This issue only appeared with a new installation of rbacon and R 4.2.2. Even with older versions of rbacon, it is the same.

Thanks for your help!

**Comment by Maarten14C** [comment]
Thanks for reporting this. I've tried to clarify the checks involved:

 negativeages <- FALSE
  if(info$postbomb == 0) # no postbomb curve selected
    if(ncol(info$dets) == 4) { # not much info on which calcurve to use
      if(info$cc > 0) # we are using C-14 dates
        if(min(info$dets[,2]) < 0) # negative C-14 ages
          negativeages <- TRUE
    } else # then we have a cc column, which is helpful
        if(max(info$dets[,5]) > 0) # using radiocarbon dates
          if(min(info$dets[which(info$dets[,5] > 0),2]) < 0) # negative C14 ages
            negativeages <- TRUE
  if(negativeages)
    stop("you have negative C14 ages so should select a postbomb curve", call.=FALSE)

**Comment by GPawi** [comment]
Thanks Maarten for the quick update. I can confirm that this solved the issue for me!
